import { useState } from 'react';
import LetterGlitch from './LetterGlitch';
import SpecularButton from './SpecularButton';

const demoRequest = {
  records: [{ asset_id: 'CBSE-EXAM-DB-01', dur: .12, proto: 'tcp', service: 'https', state: 'FIN', spkts: 6, dpkts: 4, sbytes: 125800, dbytes: 172, failed_logins: 12 }],
  signals: ['credential access', 'lateral movement', 'ransomware'],
  threat_level: 'high',
  assets: [{ asset_id: 'CBSE-EXAM-DB-01', criticality: 10, internet_exposed: true }, { asset_id: 'VPN-EDGE-01', criticality: 8, internet_exposed: true }]
};

const Icon = ({ children }) => <span className="icon" aria-hidden="true">{children}</span>;

function Landing({ enter }) {
  return <main className="landing">
    <LetterGlitch glitchSpeed={45} glitchColors={['#00F5FF', '#8A2BE2', '#3B82F6']} centerVignette outerVignette smooth />
    <nav><div className="brand"><span className="brand-mark">⌁</span><span>CYBER <b>RESILIENCE</b></span></div><span className="nav-status"><i /> PLATFORM ONLINE</span></nav>
    <section className="hero">
      <p className="eyebrow">NATIONAL CYBER RESILIENCE COMMAND</p>
      <h1>Data into<br /><em>defense.</em></h1>
      <p className="hero-copy">Enterprise-grade behavioural intelligence for critical infrastructure—compressing response time from weeks to hours.</p>
      <div className="hero-actions">
        <SpecularButton size="md" radius={999} tint="#6ff6dd" tintOpacity={0.24} blur={12} textColor="#041513" lineColor="#ffffff" baseColor="#6ff6dd" intensity={1} shineSize={14} shineFade={38} thickness={1.2} speed={0.35} followMouse proximity={220} onClick={enter}>Start monitoring</SpecularButton>
        <SpecularButton size="md" radius={999} tint="#6ff6dd" tintOpacity={0.1} blur={10} textColor="#f2fffd" lineColor="#6ff6dd" baseColor="#2b4b4f" intensity={0.8} shineSize={10} shineFade={28} thickness={1.1} speed={0.25} followMouse proximity={220} onClick={() => document.getElementById('capabilities').scrollIntoView({ behavior: 'smooth' })}>View capabilities</SpecularButton>
      </div>
      <div className="hero-meta"><span><b>01</b> Detect anomalies</span><span><b>02</b> Correlate threats</span><span><b>03</b> Orchestrate response</span></div>
    </section>
    <section id="capabilities" className="capabilities"><div><span>01 / DETECT</span><p>Baseline entities, then surface deviations without signature dependence.</p></div><div><span>02 / UNDERSTAND</span><p>Translate weak signals into ATT&CK techniques and likely campaign progression.</p></div><div><span>03 / RESPOND</span><p>Run approval-gated containment playbooks with a complete audit trail.</p></div></section>
  </main>;
}

function StatusPill({ children, tone = 'teal' }) { return <span className={`pill ${tone}`}>{children}</span>; }
function GlitchLayer() { return <LetterGlitch className="card-glitch" glitchSpeed={45} glitchColors={['#00F5FF', '#8A2BE2', '#3B82F6']} centerVignette outerVignette smooth />; }

const sections = {
  overview: ['OPERATIONAL OVERVIEW', 'Good morning, S. Kumar.', 'Your command-center summary is current.'],
  telemetry: ['LIVE TELEMETRY', 'Telemetry stream.', '2.84M events ingested in the last 24 hours.'],
  incidents: ['INCIDENT WORKSPACE', '1 active incident.', 'Suspected ransomware staging requires review.'],
  paths: ['ATTACK PATHS', 'Exposure pathways.', 'Exam database access is the highest-priority route.'],
  vulnerabilities: ['VULNERABILITY INTELLIGENCE', 'Prioritised vulnerabilities.', 'Review internet-exposed assets and critical control gaps.'],
  audit: ['AUDIT TRAIL', 'Response audit trail.', 'All response actions remain approval-gated and recorded.']
};

const sectionDetails = {
  overview: { label: 'COMMAND SUMMARY', items: ['One priority incident is awaiting analyst review.', 'Live ingestion is operating within normal latency.', 'Response controls are staged behind approval gates.'], action: 'Run threat simulation' },
  telemetry: { label: 'STREAM STATUS', items: ['2.84M events received in the last 24 hours.', 'VPN-EDGE-01 generated 12 failed authentication attempts.', 'No data-source interruption has been detected.'], action: 'Refresh telemetry' },
  incidents: { label: 'ACTIVE INCIDENT · INC-2026-071', items: ['Suspected ransomware staging on CBSE-EXAM-DB-01.', 'Correlated signals: credential access and lateral movement.', 'Containment remains simulated pending authorisation.'], action: 'Analyse incident' },
  paths: { label: 'HIGHEST-RISK ROUTE', items: ['VPN-EDGE-01 → remote services → CBSE-EXAM-DB-01.', 'DMZ segmentation is the priority control gap.', 'Reducing privileged session lifetime lowers route exposure.'], action: 'Analyse attack paths' },
  vulnerabilities: { label: 'REMEDIATION QUEUE', items: ['Internet-exposed assets should be remediated first.', 'Exam database criticality is rated 10/10.', 'Review KEV and ransomware indicators before change approval.'], action: 'Prioritise vulnerabilities' },
  audit: { label: 'AUDIT STATUS', items: ['All playbook simulations are retained in the audit log.', 'No live containment action has been executed.', 'The most recent response playbook was staged at 09:42 IST.'], action: 'View latest audit event' }
};

function Dashboard({ goHome }) {
  const [assessment, setAssessment] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [section, setSection] = useState('overview'); const [workspaceOpen, setWorkspaceOpen] = useState(false); const [profileOpen, setProfileOpen] = useState(false); const [workspace, setWorkspace] = useState('NATIONAL EDUCATION GRID'); const [ingestionLive, setIngestionLive] = useState(true); const [reviewedActions, setReviewedActions] = useState([]); const [notice, setNotice] = useState('');
  const showNotice = message => { setNotice(message); window.setTimeout(() => setNotice(''), 3600); };
  const analyse = async () => { setLoading(true); setError(''); try { const res = await fetch('/api/unified-assessment', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(demoRequest) }); if (!res.ok) throw new Error('The intelligence API is unavailable. Start the backend on port 8000.'); setAssessment(await res.json()); showNotice('Threat simulation completed. The incident workspace has been updated.'); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  const reviewAction = action => { setReviewedActions(current => current.includes(action) ? current : [...current, action]); showNotice(`${action} marked as reviewed. Approval is still required before execution.`); };
  const anomaly = assessment?.anomaly_summary?.results?.[0]; const techniques = assessment?.threat_mapping?.techniques || [];
  const selectSection = key => { setSection(key); setProfileOpen(false); };
  const [eyebrow, title, detail] = sections[section];
  const activeDetail = sectionDetails[section];
  return <main className="shell"><aside><button className="brand brand-button" onClick={goHome} aria-label="Return to landing page"><span className="brand-mark">⌁</span><span>CYBER <b>RESILIENCE</b></span></button><div className="workspace-wrap"><button className="workspace" onClick={() => setWorkspaceOpen(!workspaceOpen)} aria-expanded={workspaceOpen}>{workspace} <span>⌄</span></button>{workspaceOpen && <div className="workspace-menu"><button onClick={() => { setWorkspace('NATIONAL EDUCATION GRID'); setWorkspaceOpen(false); }}>NATIONAL EDUCATION GRID</button><button onClick={() => { setWorkspace('NATIONAL RESEARCH GRID'); setWorkspaceOpen(false); }}>NATIONAL RESEARCH GRID</button></div>}</div><div className="menu"><p>COMMAND CENTER</p><button className={section === 'overview' ? 'active' : ''} onClick={() => selectSection('overview')}><Icon>◈</Icon> Overview</button><button className={section === 'telemetry' ? 'active' : ''} onClick={() => selectSection('telemetry')}><Icon>⌁</Icon> Live telemetry</button><button className={section === 'incidents' ? 'active' : ''} onClick={() => selectSection('incidents')}><Icon>⌬</Icon> Incidents <em>1</em></button><p>INTELLIGENCE</p><button className={section === 'paths' ? 'active' : ''} onClick={() => selectSection('paths')}><Icon>◇</Icon> Attack paths</button><button className={section === 'vulnerabilities' ? 'active' : ''} onClick={() => selectSection('vulnerabilities')}><Icon>◌</Icon> Vulnerabilities</button><button className={section === 'audit' ? 'active' : ''} onClick={() => selectSection('audit')}><Icon>▤</Icon> Audit trail</button></div><div className="operator-wrap"><button className="operator" onClick={() => setProfileOpen(!profileOpen)} aria-expanded={profileOpen}><span className="avatar">SK</span><div><b>S. KUMAR</b><small>SOC ANALYST · L3</small></div><span>•••</span></button>{profileOpen && <div className="profile-menu"><b>S. Kumar</b><span>SOC Analyst · L3</span><button onClick={() => selectSection('audit')}>View activity</button><button onClick={goHome}>Exit dashboard</button></div>}</div></aside>
    <section className="command"><header><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><span className="subtle">Tuesday, 22 July 2026 · 09:42 IST · {detail}</span></div><div className="header-actions"><button className={`pill ${ingestionLive ? 'teal' : 'amber'} ingestion-toggle`} onClick={() => { setIngestionLive(!ingestionLive); showNotice(`Live ingestion ${ingestionLive ? 'paused' : 'resumed'}.`); }}>{ingestionLive ? '● LIVE INGESTION' : '● INGESTION PAUSED'}</button><button className="outline" onClick={analyse} disabled={loading}>{loading ? 'Analysing…' : 'Run threat simulation'}</button></div></header>
      {error && <div className="notice">{error}</div>}
      {notice && <div className="toast" role="status">{notice}</div>}
      {section !== 'overview' && <section className="section-detail"><div><p className="eyebrow">{activeDetail.label}</p><ul>{activeDetail.items.map(item => <li key={item}>{item}</li>)}</ul></div><button className="outline" onClick={analyse} disabled={loading}>{loading ? 'Loading…' : activeDetail.action}</button></section>}
      <section className="metrics"><SpecularButton as="article" className="metric-card" size="sm" radius={2} tint="#000000" tintOpacity={1} lineColor="#6ff6dd" baseColor="#27353a" intensity={.8} shineSize={10} shineFade={40} thickness={1} followMouse proximity={180} onClick={() => selectSection('incidents')}><span>OPEN INCIDENTS</span><strong className="critical">01</strong><small>+1 since 08:00</small></SpecularButton><SpecularButton as="article" className="metric-card" size="sm" radius={2} tint="#000000" tintOpacity={1} lineColor="#6ff6dd" baseColor="#27353a" intensity={.8} shineSize={10} shineFade={40} thickness={1} followMouse proximity={180} onClick={() => selectSection('telemetry')}><span>TELEMETRY INGESTED</span><strong>2.84M</strong><small>events in last 24h</small></SpecularButton><SpecularButton as="article" className="metric-card" size="sm" radius={2} tint="#000000" tintOpacity={1} lineColor="#6ff6dd" baseColor="#27353a" intensity={.8} shineSize={10} shineFade={40} thickness={1} followMouse proximity={180} onClick={() => selectSection('paths')}><span>BEHAVIOURAL BASELINES</span><strong>94.7%</strong><small>entity coverage</small></SpecularButton><SpecularButton as="article" className="metric-card" size="sm" radius={2} tint="#000000" tintOpacity={1} lineColor="#6ff6dd" baseColor="#27353a" intensity={.8} shineSize={10} shineFade={40} thickness={1} followMouse proximity={180} onClick={() => selectSection('audit')}><span>RESPONSE POSTURE</span><strong className="teal-text">READY</strong><small>guardrails enforced</small></SpecularButton></section>
      <section className="grid"><article className="panel incident"><GlitchLayer /><div className="panel-head"><div><p className="eyebrow">PRIORITY INCIDENT</p><h3>Suspected ransomware staging</h3></div><StatusPill tone="red">HIGH CONFIDENCE</StatusPill></div><div className="incident-body"><div className="risk-orb"><span>{anomaly ? Math.round(anomaly.anomaly_score * 100) : '—'}</span><small>RISK</small></div><div><p className="subtle">{anomaly ? anomaly.reasons.join(' · ') : 'Run simulation to score correlated signals.'}</p><div className="tag-row">{techniques.length ? techniques.map(t => <span className="tag" key={t.id}>{t.id} · {t.name}</span>) : <><span className="tag">T1110 · Brute Force</span><span className="tag">T1021 · Remote Services</span></>}</div></div></div><button className="link-button" onClick={() => { selectSection('incidents'); analyse(); }}>Open incident workspace <span>→</span></button></article>
        <article className="panel posture"><GlitchLayer /><div className="panel-head"><div><p className="eyebrow">RESILIENCE POSTURE</p><h3>Control coverage</h3></div><span className="subtle">LAST 24H</span></div><div className="bars"><div><span>Identity & access</span><b>91%</b><i><em style={{width:'91%'}} /></i></div><div><span>Network segmentation</span><b>78%</b><i><em style={{width:'78%'}} /></i></div><div><span>Endpoint response</span><b>86%</b><i><em style={{width:'86%'}} /></i></div></div><div className="posture-foot"><span>Priority gap</span><b>DMZ → Exam database</b></div></article>
      </section>
      <section className="bottom-grid"><article className="panel activity"><GlitchLayer /><div className="panel-head"><div><p className="eyebrow">THREAT TIMELINE</p><h3>Recent intelligence</h3></div><button className="text-button" onClick={() => selectSection('audit')}>View all</button></div><ul><li><span className="timeline-dot red"/><div><b>Abnormal authentication burst</b><p>VPN-EDGE-01 · 12 failed credentials</p></div><time>09:37</time></li><li><span className="timeline-dot amber"/><div><b>Lateral movement pattern observed</b><p>Remote service connection to exam database</p></div><time>09:40</time></li><li><span className="timeline-dot teal"/><div><b>Response playbook staged</b><p>Human approval required before containment</p></div><time>09:42</time></li></ul></article>
      <article className="panel actions"><GlitchLayer /><div className="panel-head"><div><p className="eyebrow">RECOMMENDED RESPONSE</p><h3>Approval gate</h3></div><StatusPill tone={reviewedActions.length === 2 ? 'teal' : 'amber'}>{reviewedActions.length === 2 ? 'REVIEWED' : 'PENDING'}</StatusPill></div><p className="subtle">Containment actions are simulated until a designated approver authorises execution.</p><div className="action-line"><span>01</span><div><b>Isolate affected endpoint</b><small>LOW BLAST RADIUS</small></div><button onClick={() => reviewAction('Isolate affected endpoint')} disabled={reviewedActions.includes('Isolate affected endpoint')}>{reviewedActions.includes('Isolate affected endpoint') ? 'Reviewed' : 'Review'}</button></div><div className="action-line"><span>02</span><div><b>Revoke privileged sessions</b><small>MEDIUM BLAST RADIUS</small></div><button onClick={() => reviewAction('Revoke privileged sessions')} disabled={reviewedActions.includes('Revoke privileged sessions')}>{reviewedActions.includes('Revoke privileged sessions') ? 'Reviewed' : 'Review'}</button></div></article></section>
    </section></main>;
}

export default function App() { const [view, setView] = useState('landing'); return view === 'landing' ? <Landing enter={() => setView('dashboard')} /> : <Dashboard goHome={() => setView('landing')} />; }
